version: '2.1'
services:
  rabbit1:
    image: rabbitmq:3.8-management
    user: "${UID}:${GID}"
    hostname: ${HOSTNAME}
    mem_limit: 2g
    restart: unless-stopped
    environment:
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
      - RABBITMQ_NODENAME=rabbit1
      - RABBITMQ_NODE_PORT=5672
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.4
    volumes:
      - ${RABBITMQ_DATA_DIR}/rabbit1:/var/lib/rabbitmq
      - ${RABBITMQ_LOGS_DIR}/rabbit1:/var/log/rabbitmq
    network_mode: "host"
  rabbit2:
    image: rabbitmq:3.8-management
    user: "${UID}:${GID}"
    hostname: ${HOSTNAME}
    mem_limit: 2g
    restart: unless-stopped
    environment:
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
      - RABBITMQ_CONFIG_FILE=/conf/rabbitmq.conf
      - RABBITMQ_NODENAME=rabbit2
      - RABBITMQ_NODE_PORT=5673
      # - RABBITMQ_SERVER_START_ARGS=-rabbitmq_management listener [{port,15673}]
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.4
    volumes:
      - ${RABBITMQ_DATA_DIR}/rabbit2:/var/lib/rabbitmq
      - ${RABBITMQ_LOGS_DIR}/rabbit2:/var/log/rabbitmq
      - ${RABBITMQ_CONF_DIR}/rabbit2:/conf
    network_mode: "host"
